sudo: false
jobs:
  include:
    - stage: Test
      language: elixir
      elixir: 1.7.4
      env: IDEA_VERSION="2019.2"
      jdk: oraclejdk8
      otp_release: 20.1
      addons:
        apt:
          packages:
            - oracle-java8-installer
      cache:
        directories:
          - cache
          - dependencies
          - "$HOME/.gradle/caches/"
          - "$HOME/.gradle/wrapper/"
      before_install:
        - mix local.hex --force
        - "export DISPLAY=:99.0"
        - "export ELIXIR_VERSION=${TRAVIS_ELIXIR_VERSION}"
        - "export ORG_GRADLE_PROJECT_elixirVersion=${TRAVIS_ELIXIR_VERSION}"
        - "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
        - "export OTP_RELEASE=${TRAVIS_OTP_RELEASE}"
        - export ERLANG_SDK_HOME=`erl -eval 'io:format("~s", [code:root_dir()]).' -noshell -run init stop`
        - export TERM=dumb
        - "sh -e /etc/init.d/xvfb start"
        - export CASHER_TIME_OUT=360
      install:
        - "./gradlew compileTestJava"
      script: travis_wait ./gradlew test
      before_cache:
        - rm -fr cache/intellij_elixir-0.1.1/rel/intellij_elixir/log
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
        - rm -fr $HOME/.gradle/caches/*/fileHashes/
    - stage: Canary Pre-Release Builds
      language: elixir
      # The earliest `elixir` support in `stage: Test`
      elixir: 1.7.4
      # The earliest `IDEA_VERSION` supported in `stage: Test`
      env:
      - IDEA_VERSION="2019.2"
      - secure: "sumWWNvahSNr7w6taGFWUXFZKsbeA5JR8qn3OI04z2sJiTE1VKYqpyJQxmJSDIALMaw7pqdF5KoUKooKJ8jIN6Dsraeg+8YS2ekYTNZL/9wFJjcjViHsscCWQhSxTEexLpUFsB1YcTscip8/nLojsgl6c4RO6zuw1d6ghjCAjak="
      jdk: oraclejdk8
      otp_release: 20.1
      cache:
        directories:
        - cache
        - dependencies
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
      before_install:
      - "export ELIXIR_VERSION=${TRAVIS_ELIXIR_VERSION}"
      - "export ORG_GRADLE_PROJECT_elixirVersion=${TRAVIS_ELIXIR_VERSION}"
      - "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
      - "export OTP_RELEASE=${TRAVIS_OTP_RELEASE}"
      - export ERLANG_SDK_HOME=`erl -eval 'io:format("~s", [code:root_dir()]).' -noshell -run init stop`
      - export TERM=dumb
      - export CASHER_TIME_OUT=360
      install: skip
      script: travis_wait ./gradlew buildPlugin
      before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      - rm -fr $HOME/.gradle/caches/*/fileHashes/
      before_deploy:
        - git config --local user.name "Luke Imhoff"
        - git config --local user.email "Kronic.Deth@gmail.com"
        - git tag --force "v$(zip_path=`ls -1 build/distributions/intellij-elixir-*.zip`; zip_name=${zip_path#build/distributions/intellij-elixir-}; echo ${zip_name%.zip})"
        - export ORG_GRADLE_PROJECT_distributionFile=`ls -1 build/distributions/intellij-elixir-*.zip`
      deploy:
        - provider: releases
          api_key:
            secure: DCGDkpqgem9/N/bJOqq0MkRGGbDLTzUVAkK9juOSb9iNdwoiY6yk2KHRV7Jn4GNjOtsLjLDPGIn3C8YhRq5z+6E0Lhp6GTKvnuFW3fdD8wrVF837TjIIBiSb1r6m/LlDSpN3w7hii8m8rEfK+63Sgm8Lt+JMpX9EniFKW8zwe50=
          file_glob: true
          file: build/distributions/intellij-elixir-*.zip
          prerelease: true
          skip_cleanup: true
          on:
            repo: KronicDeth/intellij-elixir
            branch: master
        - provider: script
          skip_cleanup: true
          script: curl --fail -F userName=KronicDeth -F password=${ORG_GRADLE_PROJECT_publishPassword} -F pluginId=7522 -F file=@${ORG_GRADLE_PROJECT_distributionFile} -F channel=canary https://plugins.jetbrains.com/plugin/uploadPlugin
          on:
            repo: KronicDeth/intellij-elixir
            branch: master
