sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
  - cache
  - dependencies
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
language: elixir
# NOTE: if you add new MAJOR IDEA versions OR change the MINOR/PATCH version numbers, update the corresponding version
# in the `runIde` and `test` run configurations, to allow for mirrored local development and test.
matrix:
  include:
    # version groups based on https://www.jetbrains.com/idea/download/previous.html

    - elixir: 1.4.5
      env: IDEA_VERSION="2017.2.5"
      jdk: oraclejdk8
      otp_release: 20.1
    - elixir: 1.4.5
      env: IDEA_VERSION="2017.2.5"
      jdk: oraclejdk8
      otp_release: 19.3

    - elixir: 1.4.5
      env: IDEA_VERSION="2017.1.5"
      jdk: oraclejdk8
      otp_release: 20.1
    - elixir: 1.4.5
      env: IDEA_VERSION="2017.1.5"
      jdk: oraclejdk8
      otp_release: 19.3

    - elixir: 1.4.5
      env: IDEA_VERSION="2016.3.7"
      jdk: oraclejdk8
      otp_release: 20.1
    - elixir: 1.4.5
      env: IDEA_VERSION="2016.3.7"
      jdk: oraclejdk8
      otp_release: 19.3

    - elixir: 1.4.5
      env: IDEA_VERSION="2016.2.5"
      jdk: oraclejdk8
      otp_release: 20.1
    - elixir: 1.4.5
      env: IDEA_VERSION="2016.2.5"
      jdk: oraclejdk8
      otp_release: 19.3
before_install:
- mix local.hex --force
- "export ELIXIR_VERSION=${TRAVIS_ELIXIR_VERSION}"
- "export ORG_GRADLE_PROJECT_elixirVersion=${TRAVIS_ELIXIR_VERSION}"
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export DISPLAY=:99.0"
- export TERM=dumb
- "sh -e /etc/init.d/xvfb start"
- "wget -v -c --header \"Cookie: oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz"
- tar xvfz jdk-8u131-linux-x64.tar.gz
- export JAVA_HOME=${PWD}/jdk1.8.0_131
- export PATH=${JAVA_HOME}/bin:${PATH}
- export CASHER_TIME_OUT=360
- java -version
install:
- ./gradlew compileTestJava
script: ./gradlew test
before_cache:
- rm -fr cache/intellij_elixir-0.1.1/rel/intellij_elixir/log
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/
sudo: false
